name: Build Plugins

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew make

    # Burası kritik: Eğer klasör ismi farklıysa bile dosyaları bulup çıkarır
    - name: Check and List Builds
      run: |
        ls -R
        mkdir -p final_builds
        find . -name "*.cs3" -exec cp {} final_builds/ \;
        find . -name "plugins.json" -exec cp {} final_builds/ \;

    - name: Push to builds branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: builds
        publish_dir: ./final_builds
        force_orphan: true
